### ISSUE TITLE
Metadata creation with x3p helper functions

### ISSUE THREAD

**Issue by srvanderplas** [heike/x3ptools#2]
Create helper functions for adding annotations and other information to x3p metadata, similar to `addtemplate_x3p`, but specific to the different options in `matrix.info`, `general.info`, `feature.info`.

Use cases
- `df_to_x3p` creates an x3p file with missing metadata for `matrix.info`, `general.info`, and `feature.info`. Creating empty files here doesn't make much sense, but it might be good to be able to create a fully specified x3p file if desired.
- `x3p_add_mask` creates a mask for the x3p file, but there is currently no way to add annotations easily and compatible with the x3p structure - you can obviously fill in a list in `matrix.info$Mask`, but this is error prone and it may not make a lot of sense to add the extra parameters to `x3p_add_mask` instead of using some abstracted helper functions. 

We may also want to add some sort of function to check and make sure the xml/information supplied conforms to the ISO standard.

**Comment by heike** [comment]
we might have to re-think how and when we are creating the meta information. 
Matrix info can be created from the existing information, the other records have to be provided by the user. 
At the moment information from a template is included when saving an x3p file in case no other information exists.
